### ISSUE TITLE
 Setting up your plugin version !

### ISSUE THREAD

**Issue by Twimmcook** [BluesatKV/jquery-tabledit#3]
Hello,

I have been trying for a long time to set up an "add" button in addition to the "edit" and "delete" buttons. Apparently your little version do it?
I wanted to follow these tutorials:
https://www.youtube.com/watch?v=Xhl6UC3nsnE
https://www.youtube.com/watch?v=75WnV-Suzkk&t=3s
But I have a lot of trouble setting everything up, I'm not a developer.
So, I found your version of Tabledit.
If I understand correctly, it takes 4 files (index.php, 1 file javascript, 1 file to "edit" and "delete", 1 file to "add row") ???
I also see the addition of a line at the end of the table. Would not it be better to add to the first line?
How to set everything up to be sure that the "add" button works, as well as "edit" and "delete" buttons?
Thank you for this version that could help me!

**Comment by TomZ79** [comment]
Hi Twimmcook, 
thx for isssue :-)

**Example with Add row**
[https://bluesatkv.github.io/jquery-tabledit/#examples9](https://bluesatkv.github.io/jquery-tabledit/#examples9)

**Required files**
[https://github.com/BluesatKV/jquery-tabledit](https://github.com/BluesatKV/jquery-tabledit)

- jquery.js
- jquery.tabledit.js
- config file script (Config Tabledit and button 'Add new row')
- php file for "add new row" -> Tabs 'PHP Save edit or delete rows in table' in Example #9
- php file for "tabledit plugin (save, edit, restore, delete) -> Tabs 'PHP Add new row to DB' in Example #9

**Config file script**
Tabs 'Javascript' in Example #9

- Config for Tabledit plugin on table element
- Config Ajax for click button 'Add new row'

**The logic of adding a new row**

1 . After click button 'Add new row' call Ajax. 
2.  Sending data over Ajax to php script
3. Php script insert data to your DB (e.g. MySQL), get all dat from DB and revert data back to Ajax.
4. Jquery script processes data from php and rewrite whole table. 

> I also see the addition of a line at the end of the table. Would not it be better to add to the first line

Yes and no :-) PHP script can revert html data for Ajax with sort by different parameter. 

Example (php script in Example #9 for 'Add new row' and select all data ORDER BY ID ASC):

It's only example.

```
// Get value from ajax
$variable = $_POST['somevalue'];

// Php question

   /*  Your code for insert data to DB - add new row to DB */
  $db->query('INSERT db_table SET id = NULL,  column1= "' .  $variable. '", column2= ""');

  /*  Your code for select all data from DB to rewrite your table - **ORDER BY ID ASC** */
  $result = $db->query('SELECT * FROM db_table  WHERE column1= "' . $$variable. '" ORDER BY id ASC');

```

Example (php script in Example #9 for 'Add new row' and select all data ORDER BY ID DESC):

It's only example.

```
// Get value from ajax
$variable = $_POST['somevalue'];

// Php question

   /*  Your code for insert data to DB - add new row to DB */
  $db->query('INSERT db_table SET id = NULL,  column1= "' .  $variable. '", column2= ""');

  /*  Your code for select all data from DB to rewrite your table - **ORDER BY ID DESC** */
  $result = $db->query('SELECT * FROM db_table  WHERE column1= "' . $$variable. '" ORDER BY id DESC');

```

and more other examples :-)

> How to set everything up to be sure that the "add" button works, as well as "edit" and "delete" buttons?

- you must have a good jquery Ajax script and if you have problems, use the console web browser

**Comment by TomZ79** [comment]
Twimmcook,

I will prepare a special example with the addition of one row.

**Comment by Twimmcook** [comment]
Following my problem quoted here [https://github.com/markcell/jquery-tabledit/issues/72](https://github.com/markcell/jquery-tabledit/issues/72), I test your version of jquery-tabledit.min.js
When I refresh my page, for half a second, I see the column with the title Actions, but then the column goes back to my initial problem.

**Comment by TomZ79** [comment]
Put your code please.

**Comment by Twimmcook** [comment]
My function Tabledit

`$('#ingredients_table').Tabledit( {
      	url:'../pages/action.php',
      	editButton: true,
		deleteButton: true,
		restoreButton:false,
		hideIdentifier: true,
		/* Custom buttons */
		groupClass: 'btn btn-xs',
		buttons: {
		   	edit: {
		   		class: 'btn btn-xs btn-default',
		   		html: '<span class="glyphicon glyphicon-pencil"></span>',
		   		action: 'edit'
		   	},
		   	delete: {
		   		class: 'btn btn-xs btn-default',
		   		html: '<span class="glyphicon glyphicon-trash"></span>',
		   		action: 'delete'
		   	},
		   	save: {
		   		class: 'btn btn-xs btn-success',
		   		html: 'Sauvegarder'
		   	},
		   	confirm: {
		   		class: 'btn btn-xs btn-danger',
		   		html: 'Confirmer'
		   	}
		},
      	columns: {
       		identifier:[0, "id"],
       		editable:[[1, 'familles'], [2, 'ingredients'], [3, 'fournisseurs'], [4, 'prix'], [5, 'unites']]
      	},
      	onSuccess:function(data, textStatus, jqXHR)	{
       		if(data.action == 'delete') {
        		$('#'+data.id).remove();
       		}
      	}
    });`

PHP edit and delete

`<?php  
//action.php
require_once( '../app/table/functions.php' );
mysqli_set_charset($connect, "utf8");

$input = filter_input_array(INPUT_POST);

$familles = mysqli_real_escape_string($connect, $input["familles"]);
$ingredients = mysqli_real_escape_string($connect, $input["ingredients"]);
$fournisseurs = mysqli_real_escape_string($connect, $input["fournisseurs"]);
$prix = mysqli_real_escape_string($connect, $input["prix"]);
$unites = mysqli_real_escape_string($connect, $input["unites"]);

if($input["action"] === 'edit')
{
 $query = " UPDATE ingredients
 			SET familles_id = '".$familles."', 
 				ingredients = '".$ingredients."',
 				fournisseurs = '".$fournisseurs."',
 				prix = '".$prix."',
 				unites_id = '".$unites."' 
 			WHERE id = '".$input["id"]."' ";

 mysqli_query($connect, $query);

}
if($input["action"] === 'delete')
{
 $query = " DELETE FROM ingredients 
 			WHERE id = '".$input["id"]."' ";
mysqli_query($connect, $query);
}

echo json_encode($input);

?>`

PHP add button

`<?php
//insert.php  
require_once( '../app/table/functions.php' );
mysqli_set_charset($connect, "utf8");

if(isset($_POST["familles"], $_POST["ingredients"], $_POST["fournisseurs"], $_POST["prix"], $_POST["unites"]))
{
 $output = '';
    $familles = mysqli_real_escape_string($connect, $_POST["familles"]);  
    $ingredients = mysqli_real_escape_string($connect, $_POST["ingredients"]);  
    $fournisseurs = mysqli_real_escape_string($connect, $_POST["fournisseurs"]);  
    $prix = mysqli_real_escape_string($connect, $_POST["prix"]);  
    $unites = mysqli_real_escape_string($connect, $_POST["unites"]);
    $query = "
    INSERT INTO ingredients(familles_id, ingredients, fournisseurs, prix, unites_id)  
     VALUES('$familles', '$ingredients', '$fournisseurs', '$prix', '$unites')
    ";
    if(mysqli_query($connect, $query))
    {
      echo 'Ingrédient ajouté !';
    }
}
?>`

**Comment by TomZ79** [comment]
Hi,

Jquery init code is OK. 

Problem will be it in other Jquery plugin for table. What plugin do you use? Datatable?

**Comment by Twimmcook** [comment]
In my JS folder, i have : 
- jquery-3.1.1.min.js
- jquery.dataTables.min.js
- jquery.tabledit.min.js (your version)
- bootstrap.min.js
- dataTables.bootstrap.min.js
- main.js (my custom function js)

**Comment by TomZ79** [comment]
I will test tonight

**Comment by TomZ79** [comment]
First solution :-)

Init Tabledit plugin before dataTables  plugin and works. 

![jq_tabledit_01](https://user-images.githubusercontent.com/20857152/30020132-1b2a9560-9163-11e7-8833-f34c4c3ee0fd.jpg)

NOTE:  Use jquery.tabledit.js (1.2.7 DEV - I prepared small fix for using plugin with datatable) (Download now with fix)

**Comment by TomZ79** [comment]
I prepared new version with new parameter `toolbarHeaderClass: 'no-sort'` .

New class is for adding custom class to toolbar header column. 

![jq_tabledit_02](https://user-images.githubusercontent.com/20857152/30021391-82998c48-9167-11e7-9124-ebe511ab16ff.jpg)

Download now with fix ;-)

**Comment by Twimmcook** [comment]
// LANGUAGE/LOCALIZATION
  $.fn.Tabledit.langs = {
   fr: {
      btn_edit: 'Editer',
      btn_delete: 'Supprimer',
      btn_confirm: 'Confirmer',
      btn_save: 'Enregistrer',
      btn_restore: 'Restaurer',
      txt_action: 'Actions',
      txt_nolimit: 'Nombre de caractères sans limite',
      txt_allowchar: 'Nombre de caractères autorisés %s',
      txt_remain: 'caractères restants'
    },

;-)

**Comment by Twimmcook** [comment]
I don't know what happend.
When i put F5 to refresh my table it's the same problem.
Actions columns appears and disappears very quickly

**Comment by TomZ79** [comment]
All works good. Example with DataTable Plugin

[https://jsfiddle.net/BluesatKV/ftgfw3s5/](https://jsfiddle.net/BluesatKV/ftgfw3s5/)

or 

[https://jsfiddle.net/BluesatKV/ftgfw3s5/8/](https://jsfiddle.net/BluesatKV/ftgfw3s5/8/)

Maybe the problem is still somewhere else.

**Comment by Twimmcook** [comment]
OK, I do not understand. The problem has to come from elsewhere, but I do not know where ...
Thanks anyway !

**Comment by TomZ79** [comment]
Some conflict in Jquery or Jqeury plugin. Check console fo web browser. 

Good luck.
