### ISSUE TITLE
Datatables

### ISSUE THREAD

**Issue by hogendoorn** [BluesatKV/jquery-tabledit#4]
Hi,

Creat to see the project going one! But when i use it incombination with datatables only the firt page shows the actions buttons. Going to the next page the buttons (Edit/Delete ) are gone.

Thanks

Michael

**Comment by TomZ79** [comment]
I'll check next week. Can you send me your datatables config please?

**Comment by hogendoorn** [comment]
Sure:
```
 $('#item-table').DataTable({
   "dom": '<"top"i>rt<"bottom"fp><"clear">'	
 });	
```
Its also happening with zero configuration.

**Comment by hogendoorn** [comment]
hi BluesatKV, did you had the change to lookin to this issue ?
