### ISSUE TITLE
Improvement request: onAjax() return handling

### ISSUE THREAD

**Issue by bjoernwuest** [BluesatKV/jquery-tabledit#6]
### Current situation:
when returning 'false' in onAjax() function, tabledit stops the whole ajax operation. Otherwise, tabledit continues ajax operation but without considering any changes that may happen during onAjax() invocation.

### Proposed situation:
in function 'ajax(action)', change of code
`if (result === false) { return false; }`
into
`if (result === false) { return false; } else { serialize = result; }`

### Motivation:
Now, in onAjax() it is possible to modify the document sent in ajax request, e.g. adding additional information required by server, or do formatting / restructing of document to be sent.

**Comment by TomZ79** [comment]
Thanks

Commits on Apr 15, 2018
d635c66eca83cd260e2b474393afb7d3cdbe9fec
